[package]
name = "mice"
version = "0.1.0"
edition = "2021"
authors = ["Emre Bicer <oebicer@gmail.com>"]
license = "MIT"
description = "A library that aims to help simulating mouse actions across different platforms."
homepage = "https://github.com/emrebicer/mice"
repository = "https://github.com/emrebicer/mice"
readme = "README.md"
keywords = ["mouse", "movement", "click", "scroll", "events"]
categories = ["accessibility"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
